apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
spec:
  selector:
    matchLabels:
      app: todo-backend
      tier: backend
      track: stable
  replicas: 2
  template:
    metadata:
      labels:
        app: todo-backend
        tier: backend
        track: stable
    spec:
      containers:
        - name: todo-backend
          image: k3d-test-app-registry:5050/todo-api-new:v1.0
          imagePullPolicy: Always
          env:
            - name: DB_URL
              value: "jdbc:mysql://mysql/todo"
            - name: DB_USERNAME
              value: "helloworld"
            - name: DB_PASSWORD
              value: "password"
            - name: DB_DDL_AUTO
              value: "none"
          ports:
            - name: http
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: todo-backend
spec:
  type: NodePort
  selector:
    app: todo-backend
    tier: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-backend
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: todo-backend
                port:
                  number: 80